# Generated by Django 5.0.6 on 2026-08-13 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ชื่อ-นามสกุล')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ผู้ดูแลระบบ',
                'verbose_name_plural': 'ผู้ดูแลระบบ',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='รหัสนักเรียน')),
                ('full_name', models.CharField(max_length=150, verbose_name='ชื่อ-นามสกุล')),
                ('class_name', models.CharField(blank=True, max_length=50, verbose_name='ชั้นเรียน')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='เบอร์โทรศัพท์')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='อีเมล')),
                ('status', models.CharField(choices=[('active', 'ปกติ'), ('suspended', 'ระงับการยืม')], default='active', max_length=20, verbose_name='สถานะ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'สมาชิก',
                'verbose_name_plural': 'สมาชิก',
            },
        ),
    ]
